# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Organisateur.create(:nom=>"C'est pas sorcier", :description => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas gravida quam et purus feugiat auctor tincidunt tortor facilisis. Maecenas nec mi velit. Duis mollis lorem at turpis tempus nec vehicula risus placerat. Duis sed ligula id risus iaculis ullamcorper. Nunc eu ante ipsum, in porttitor eros. Integer eget libero nec felis aliquet malesuada eget mollis orci. Donec adipiscing adipiscing congue. Suspendisse potenti. Nam eget dolor ut lorem consequat vestibulum ac vitae metus.\r\n\r\nNam tempor aliquet congue. Maecenas sapien mauris, molestie sagittis lobortis tincidunt, varius sit amet metus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel diam nulla. Duis erat orci, hendrerit sit amet semper eget, porttitor nec libero. Praesent ut tempor arcu. Integer id purus quis odio rhoncus tristique. Pellentesque eu nisl sit amet nibh placerat volutpat nec vel risus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ultricies ullamcorper libero ac accumsan. Phasellus varius adipiscing felis, ac consequat risus eleifend vitae. Cras neque orci, rhoncus ut hendrerit sed, venenatis vitae dui.", :avatar=>"960e191e829a7256181ec0e188607898.JPG")
Organisateur.create(:nom=>"Franklin", :description =>"Maecenas dictum lacinia dui eu ultrices. Phasellus venenatis aliquet venenatis. Proin dapibus nisl a lectus accumsan volutpat. Curabitur mattis, quam nec ornare vehicula, nisi purus aliquet justo, a dictum purus dui et dui. Integer lectus tortor, tincidunt eget placerat quis, fermentum sit amet arcu. Nulla id sem lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce mi sapien, bibendum eget suscipit ac, eleifend eu leo. Donec laoreet tincidunt orci. Sed et tincidunt lorem. In hac habitasse platea dictumst. Ut et ipsum dui, et posuere mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus est velit, malesuada non cursus vitae, consectetur vel odio. Aliquam dui nulla, scelerisque vitae bibendum id, malesuada id orci." , :avatar=>"977d6062243e8be5ef367a174c7fc6ee.png")
Organisateur.create(:nom=>"Platon and co ", :description =>"Nam tempor aliquet congue. Maecenas sapien mauris, molestie sagittis lobortis tincidunt, varius sit amet metus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel diam nulla. Duis erat orci, hendrerit sit amet semper eget, porttitor nec libero. Praesent ut tempor arcu. Integer id purus quis odio rhoncus tristique. Pellentesque eu nisl sit amet nibh placerat volutpat nec vel risus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ultricies ullamcorper libero ac accumsan. Phasellus varius adipiscing felis, ac consequat risus eleifend vitae. Cras neque orci, rhoncus ut hendrerit sed, venenatis vitae dui.\r\n\r\nSed ornare facilisis augue quis cursus. Cras mattis quam nec diam condimentum convallis. Curabitur cursus lorem non leo vehicula imperdiet. Nunc gravida tincidunt cursus. Etiam vulputate iaculis ipsum, vel cursus diam elementum non. Nullam vitae augue mauris. Ut ut risus ante, feugiat molestie nibh. Aliquam rutrum dictum sem a malesuada." , :avatar=>"00509113c3866a934f5eec962a649076.jpg")
Organisateur.create(:nom=>"Gourmet gourmand", :description => "Maecenas dictum lacinia dui eu ultrices. Phasellus venenatis aliquet venenatis. Proin dapibus nisl a lectus accumsan volutpat. Curabitur mattis, quam nec ornare vehicula, nisi purus aliquet justo, a dictum purus dui et dui. Integer lectus tortor, tincidunt eget placerat quis, fermentum sit amet arcu. Nulla id sem lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Fusce mi sapien, bibendum eget suscipit ac, eleifend eu leo. Donec laoreet tincidunt orci. Sed et tincidunt lorem. In hac habitasse platea dictumst. Ut et ipsum dui, et posuere mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus est velit, malesuada non cursus vitae, consectetur vel odio. Aliquam dui nulla, scelerisque vitae bibendum id, malesuada id orci.", :avatar=>"19f451e1cd48c597c4b486050f1a271a.png")
Organisateur.create(:nom=>"In Sevilla ", :description => "Suspendisse lorem erat, condimentum et adipiscing in, egestas quis lorem. Curabitur tempor sollicitudin magna, id pellentesque augue ullamcorper at. Cras tristique mattis nisi, eu gravida enim bibendum sed. Mauris vehicula vestibulum gravida. Sed nec condimentum ligula. Morbi massa neque, fermentum ut luctus in, adipiscing quis lectus.", :avatar=>"327a04bd82ddd0fe3a93f5cb05a3fe36.jpg")